config/routes.rb
Rails.application.routes.draw do
  root to: 'promocodes#index'
  devise_for :users
  resources :promocodes
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/promocode.rb
class Promocode < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :promocodes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/promocodes_controller.rb
class PromocodesController < ApplicationController
  before_action :set_promocode, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /promocodes
  # GET /promocodes.json
  def index
    @promocodes = Promocode.all
  end

  # GET /promocodes/1
  # GET /promocodes/1.json
  def show
  end

  # GET /promocodes/new
  def new
    @promocode = Promocode.new
  end

  # GET /promocodes/1/edit
  def edit
  end

  # POST /promocodes
  # POST /promocodes.json
  def create
    @promocode = Promocode.new(promocode_params)
    @promocode.user = current_user
    respond_to do |format|
      if @promocode.save
        format.html { redirect_to @promocode, notice: 'Promocode was successfully created.' }
        format.json { render :show, status: :created, location: @promocode }
      else
        format.html { render :new }
        format.json { render json: @promocode.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /promocodes/1
  # PATCH/PUT /promocodes/1.json
  def update
    respond_to do |format|
      if @promocode.update(promocode_params)
        format.html { redirect_to @promocode, notice: 'Promocode was successfully updated.' }
        format.json { render :show, status: :ok, location: @promocode }
      else
        format.html { render :edit }
        format.json { render json: @promocode.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /promocodes/1
  # DELETE /promocodes/1.json
  def destroy
    @promocode.destroy
    respond_to do |format|
      format.html { redirect_to promocodes_url, notice: 'Promocode was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_promocode
      @promocode = Promocode.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def promocode_params
      params.require(:promocode).permit(:code_title, :code_hashtag)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/promocodes_helper.rb
module PromocodesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Oibt06</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/promocodes/_form.html.erb
<%= simple_form_for(@promocode) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :code_title %>
    <%= f.input :code_hashtag %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/promocodes/edit.html.erb
<h1>Editing Promocode</h1>

<%= render 'form', promocode: @promocode %>

<%= link_to 'Show', @promocode %> |
<%= link_to 'Back', promocodes_path %>

app/views/promocodes/index.html.erb
<h1>디플로이는 되었다. 이제 다시 시작하다!!!</h1>


<% if current_user %>
  <%= link_to 'Sign out', destroy_user_session_path, method: :delete %>
<% else %>
  <%= link_to 'Sign up', new_user_registration_path %>
  <%= link_to 'Sign in', new_user_session_path %>
<% end %>





<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Hastag</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @promocodes.each do |promocode| %>
      <tr>
        <td><%= promocode.code_title %></td>
        <% if current_user && current_user.admin %>
          <td><%= promocode.code_hashtag %></td>
          <td><%= link_to 'Show', promocode %></td>
          <td><%= link_to 'Edit', edit_promocode_path(promocode) %></td>
          <td><%= link_to 'Destroy', promocode, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Promocode', new_promocode_path %>

app/views/promocodes/new.html.erb
<h1>New Promocode</h1>

<%= render 'form', promocode: @promocode %>

<%= link_to 'Back', promocodes_path %>

app/views/promocodes/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @promocode.code_title %>
</p>

<p>
  <strong>Hastag:</strong>
  <%= @promocode.code_hashtag %>
</p>

<%= link_to 'Edit', edit_promocode_path(@promocode) %> |
<%= link_to 'Back', promocodes_path %>